
server:
  port: ${port:9000} # 未指定端口则默认9000


spring:
  application:
    name: hs-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 61a984f0-4cf0-4e5c-94cf-cedb7962eaaa
logging:
  level:
    root: info
    org.springframework: info