
server:
  port: ${port:9000} # 默认端口9000 可以根据启动vm参数变更端口号


spring:
  application:
    name: hs-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    root: info
    org.springframework: info