
server:
  port: 9050


spring:
  application:
    name: hs-consumer
  cloud:
    nacos:
      discovery:
        enabled: false # 纯消费者,不暴露服务
        server-addr: 127.0.0.1:8848
        namespace: 61a984f0-4cf0-4e5c-94cf-cedb7962eaaa
        cluster-name: DEFAULT

logging:
  level:
    root: info
    org.springframework: info